### PR TITLE
(DOCSP-30890) [UI] Make component mobile responsive

### PR DESCRIPTION
**Pull request by nlarew**
Jira: (DOCSP-30890) [UI] Make component mobile responsive

## Proposed Changes

- Responsive styles for Small, Medium, and Large+ screens ([as defined in Snooty](https://github.com/mongodb/snooty/blob/master/src/theme/docsTheme.js#L39-L47))
- Adds a modal close button

### CODE REVIEW

**Comment by mongodben** [comment]
there's some x-overflow, though it is scrollable. why not just make the content wrap? 
Screenshot 2023-07-07 at 10 20 28 AM

**Review by mongodben — CHANGES_REQUESTED** [review]
there's some x-overflow, though it is scrollable. can you make the content fit the width and wrap? 
Screenshot 2023-07-07 at 10 20 28 AM

**Comment by mongodben** [comment]
also, on further thought, if you think this work will be rendered irrelevant when we use the leafy green components, i don't think we need to belabor it

**Comment by nlarew** [comment]
@mongodben fixed this for now with a small CSS hack. Should go away / be "not our problem" with the LG Chat components.

**Pull request merged**
